### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by hickford** [lehrblogger/OkCupid-Message-Downloader#28]
Consider publishing a package to PyPI so the app is easier to install

    pip install OkCupid-Message-Downloader

https://pypi.python.org/pypi

**Comment by hickford** [comment]
This is a great app, thanks

**Comment by joelpurra** [comment]
@hickford: guess that would be convenient =)

@lehrblogger: it's probably best if you publish to pypi from your own account, right?

**Comment by lehrblogger** [comment]
@joelpurra Yeah, I should have a chance to do it in the next few days :)

**Comment by lehrblogger** [comment]
I published something to the test PyPI, but I'm not sure that it's

**Comment by lehrblogger** [comment]
This was my first time publishing to PyPI, but was able to get it on `pypitest` using [this guide](http://peterdowns.com/posts/first-time-with-pypi.html). I had to reorganize the directory structure a bit to get it to upload, and hopefully I didn't break anything. I was able to install the package from there with `pip install -i https://testpypi.python.org/pypi OkCupid-Message-Downloader`, but it seems to only have installed the contents of the `OkCupid-Message-Downloader` directory with the actual python script, and not the `okcmd` wrapper.

I could move `okcmd` into the package, but it doesn't really belong there either, and I like how it sets up the virtualenv so wouldn't want to scrap that. @joelpurra, thoughts? Maybe the `git clone` isn't so inconvenient after all, since this isn't really a normal package?

(Regardless, I need to change the package name to not include any `-`'s before publishing to the actual PyPI.)

**Comment by joelpurra** [comment]
@lehrblogger wrote:
> it seems to only have installed the contents of the `OkCupid-Message-Downloader` directory with the actual python script, and not the `okcmd` wrapper.

Found `scripts` which seems to be pretty generic and should work for bash scripts, and `console_scripts` which seems to be for python scripts which will have wrapper scripts generated for them. Did you look at those?
https://docs.python.org/3.4/distutils/setupscript.html#installing-scripts

Specifying `scripts` should include it in the distribution, but you can also specify other files (data and metadata) to be included. It doesn't seem as if the `LICENSE` file is included at the moment btw.
https://docs.python.org/3.4/distutils/sourcedist.html#manifest


> I could move `okcmd` into the package, but it doesn't really belong there either, and I like how it sets up the virtualenv so wouldn't want to scrap that. @joelpurra, thoughts? Maybe the `git clone` isn't so inconvenient after all, since this isn't really a normal package?

Given the issues reported when it came to python and BeautifulSoup version differences, I much prefer locking them down with the `okcmd` wrapper script. I'm personally ok with `git clone`, but can see how a package manager would help non-devs.

Not sure if there's a convenient way to replace the `okcmd` wrapper with an equivalent `virtualenv` (with `--no-site-packages`) wrapper written in python -- or if `pip install OkCupid-Message-Downloader` itself with the right `setup.py` options might remove the need for `okcmd` altogether?
https://virtualenv.pypa.io/en/latest/reference.html#extending-virtualenv

**Comment by lehrblogger** [comment]
@joelpurra, thanks for those suggestions! Sorry for the delay, I had a busy week.

After some trial and error (above) I think I've got it working, but haven't published it to to PyPi proper yet. You should be able to install it with `pip install -i https://testpypi.python.org/pypi okcmd`, and then run `okcmd` as normal. I don't love the current location of the `requirements.txt` file, but wasn't sure where it belonged. Any suggestions?

**Comment by joelpurra** [comment]
@lehrblogger: looking at the troubles with the installation location (and subsequently the virtual environment), I'm thinking it might be best to leave the bash script out of the pypi package.

How about adding a `console_scripts` entry for the python script, naming it `okcmd`, so it's installed in the system `PATH`? This way the pypi package would do pretty much the same thing as the bash script -- and it would be closer to the one true pypi way™®©.

If so, the bash script files could be excluded from the package, which would also allow reverting the location of the bash script to the root of the git repository. Those cloning the repo would then also be able to run it with `okcmd` as before.

Best of both worlds?

**Comment by lehrblogger** [comment]
@joelpurra Ah, yeah, I think that could work, and would feel much more Correct than what I have so far :)

The one thing for which I thought we still needed the `virtualenv` was ensuring that it was using the desired version of Python, since you mentioned issues with other versions. Do you think specifying it [with `classifiers` in `setup.py`](https://packaging.python.org/en/latest/distributing.html#classifiers) would be sufficient? Which versions are ok?

**Comment by joelpurra** [comment]
@lehrblogger: I'd go for python2.7 at the moment, as some packages have been renamed for python3. Think there are also some unicode changes as well, and those kinds of low-level changes can be tricky.

You can see some suggested code changes by running `2to3`:

```bash
2to3-3.4 arrow_fetcher.py | git apply
```

Unfortunately the resulting patch is incomplete; got this error: `TypeError: 'str' does not support the buffer interface` during a test run and decided to stop there.

Stick with 2.7 for now. We can always upgrade to 3 (while also keeping it backwards compatible?) at a later point.

**Comment by lehrblogger** [comment]
@joelpurra, yeah, that makes sense. It now seems to be running properly using both install methods.

I moved the bash script and `requirements.txt` back to the root of the repository. I had to add a `.sh` to the script name so that I could name the folder `okcmd` though.

Note that with the testpypi installation you'll need to run `pip install beautifulsoup4==4.4.0` before `pip install -i https://testpypi.python.org/pypi okcmd` because it seems like the actual `4.4.0` release isn't on the test PyPI.

Any other changes you would suggest before releasing to PyPI proper?

**Comment by joelpurra** [comment]
@lehrblogger wrote:
> @joelpurra, yeah, that makes sense. It now seems to be running properly using both install methods.

Great! Installing from the test server (with BS4 workaround) worked well for me.


> I moved the bash script and requirements.txt back to the root of the repository. I had to add a .sh to the script name so that I could name the folder okcmd though.

While it could be a question of merely documenting the difference between cloning (with out without manually setting `$PATH`) and pypi, how about renaming the `okcmd` directory with `package_dir`?
https://docs.python.org/3.4/distutils/setupscript.html#listing-whole-packages


> Any other changes you would suggest before releasing to PyPI proper?

I'd say renaming the directory would be good to fix before releasing. Installing with `pip` hasn't been documented in `README.md` though, so guess that'd be the final thing.

**Comment by lehrblogger** [comment]
Great suggestion about the `package_dir`! That's definitely more usable. I also updated the `README`, bumped it to v1.0, and cleaned up my test tags before publishing to PyPi:

 - [https://pypi.python.org/pypi/okcmd/1.0](https://pypi.python.org/pypi/okcmd/1.0)

Thanks for your help and suggestions! And thanks @hickford for opening the issue :)

**Comment by joelpurra** [comment]
@lehrblogger: looks great!

Added some more information to `okcmd --help` (description, project link) and restructured the README. Added the `pip install okcmd` command and labeled cloning the repository as "advanced" so hope most people will use the package.

Have a look, and possibly push a new package version =)

**Comment by lehrblogger** [comment]
Thanks! Those changes definitely make things easier to understand, and I published a new version to PyPI.
