### ISSUE TITLE
Sort downloads by other user

### ISSUE THREAD

**Issue by nomeata** [lehrblogger/OkCupid-Message-Downloader#39]
Hi,

it would be nice if the tool could (optionally) not write to one text file, but rather to a number of text files corresponding to the users that I have chatted with. This makes it easier to retrace a conversation with one other person.

Thanks,
joachim

**Comment by nomeata** [comment]
Working on a patch...

**Comment by lehrblogger** [comment]
Good idea! I'll take a look this weekend if no one beats me to it.

**Comment by nomeata** [comment]
More boldly, I wonder if there are users who would not prefer a per-user-user file over a single file, and maybe it’s worth simplifying the code to only provide that option. But I’ll leave that to you :-)

**Comment by joelpurra** [comment]
@lehrblogger wrote:
> Good idea! I'll take a look this weekend if no one beats me to it.

Agree! Don't expect to have time to dissect the commit, but hope to test it when I have a stable enough connection.


@nomeata wrote: 
> More boldly, I wonder if there are users who would not prefer a per-user-user file over a single file, and maybe it’s worth simplifying the code to only provide that option. But I’ll leave that to you :-)

I'd keep it as an option for now, and let users get used to having it, then we'll see.

More urgently I'd like to see a refactoring of the code -- I'm sure there are some blocks which would look much better as methods, and perhaps even some which can be logically grouped as classes. Assuming this patch is good (and perhaps #38?) I'd save refactoring until after the merge.

**Comment by lehrblogger** [comment]
Sorry for the delay! Last weekend and the week since were busier than expected.

This change looks/works great, except I got a `IOError: [Errno 24] Too many open files` error on my personal account after fetching 543 threads. Granted I was probably a heavier user than most, but it's still something we should handle, perhaps by closing whichever have been written to most recently?

I agree with keeping it as an option for now, but :+1: on some refactoring. My only hesitance re #38 is due to coercing all the emoji that kids use these days into ascii.

**Comment by nomeata** [comment]
I should simply write out each file in progression. I was under the impression that you read the data incrementally from okcupid, but that’s not actually the case. I can re-structure the code to simply write one file at a time.

**Comment by nomeata** [comment]
Pull request updated.

**Comment by lehrblogger** [comment]
Merged – thanks again! Writing one file at a time is a much better solution, I must have been more tired last night than I realized.

I'll bump the version number and publish to PyPI.
